# Build settings
markdown: kramdown

url: https://ncna.icpc.io/north-central-website # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g., /blog/ //SM keep blank

exclude: [
 package.json,
 Gruntfile.js,
 node_modules,
 .sass-cache,
 Gemfile,
 Gemfile.lock,
 .gitignore
]

# Theme Settings
analytics:
google_verification:

# Contact form
api_token: # Enter API token here
